// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzsisvt3CnA4pE3uyRoGAllAKSeFKRw4',
    appId: '1:221424984740:web:36bd7d0a7ba911ea86fc31',
    messagingSenderId: '221424984740',
    projectId: 'graduation-demo',
    authDomain: 'graduation-demo.firebaseapp.com',
    storageBucket: 'graduation-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeHhbRE_2kVOgfTIx5fwTe7zeui8BqSU',
    appId: '1:221424984740:android:e552efb5e69efb6e86fc31',
    messagingSenderId: '221424984740',
    projectId: 'graduation-demo',
    storageBucket: 'graduation-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGEKA0wJc6kOUL1DKtajeM7zK5CajYkk',
    appId: '1:221424984740:ios:172e1195a844be0e86fc31',
    messagingSenderId: '221424984740',
    projectId: 'graduation-demo',
    storageBucket: 'graduation-demo.appspot.com',
    iosBundleId: 'com.example.pulsePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGEKA0wJc6kOUL1DKtajeM7zK5CajYkk',
    appId: '1:221424984740:ios:172e1195a844be0e86fc31',
    messagingSenderId: '221424984740',
    projectId: 'graduation-demo',
    storageBucket: 'graduation-demo.appspot.com',
    iosBundleId: 'com.example.pulsePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzsisvt3CnA4pE3uyRoGAllAKSeFKRw4',
    appId: '1:221424984740:web:4bb00f1f82e4359a86fc31',
    messagingSenderId: '221424984740',
    projectId: 'graduation-demo',
    authDomain: 'graduation-demo.firebaseapp.com',
    storageBucket: 'graduation-demo.appspot.com',
  );
}
